# Generated by Django 2.0 on 2017-12-23 21:41

from django.db import migrations

def create_intial_scores(apps, schema_editor):
    NFLScore = apps.get_model('api', 'NFLScore')

    NFLScore(gameId=1, homeTeam='NYG', homeScore=0, awayTeam= 'ATL', awayScore= 0, gameStatus= 'SCHEDULED', currentQuarter= 0, currentTime= '15=00',
      gameTime= '10-DEC-2017 8=30 EST', homeLosses= 2, homeWins= 0, awayWins= 2, awayLosses= 0, awayq1Score= 0, awayq2Score= 0, awayq3Score= 0, awayq4Score= 0,
      homeq1Score= 0, homeq2Score= 0, homeq3Score= 0, homeq4Score= 0).save()
    NFLScore(gameId= 2, homeTeam= 'NYJ', homeScore= 0, awayTeam= 'NE', awayScore= 23, gameStatus= 'LIVE', currentQuarter= 2, currentTime= '15=00',
      gameTime= '10-DEC-2017 4=15 EST', homeLosses= 2, homeWins= 0, awayWins= 2, awayLosses= 0, awayq1Score= 7, awayq2Score= 0, awayq3Score= 0, awayq4Score= 0,
      homeq1Score= 3, homeq2Score= 0, homeq3Score= 0, homeq4Score= 0).save()
    NFLScore(gameId= 3, homeTeam= 'WAS', homeScore= 10, awayTeam= 'PHI', awayScore= 0, gameStatus= 'FINAL', currentQuarter= 4, currentTime= '0=00',
      gameTime= '10-DEC-2017 1=00 EST', homeLosses= 2, homeWins= 0, awayWins= 2, awayLosses= 0, awayq1Score= 7, awayq2Score= 7, awayq3Score= 7, awayq4Score= 7,
      homeq1Score= 3, homeq2Score= 3, homeq3Score= 3, homeq4Score= 3).save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_intial_scores),
    ]
